# Generated by Django 3.0 on 2020-03-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='dob',
            new_name='age',
        ),
    ]
