# Generated by Django 3.0 on 2020-03-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20200323_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD format'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_site',
            field=models.URLField(blank=True, help_text='Note: Add https:// in the URL, Example: https://youtu.be/r2Hvxr7esNM ', unique=True),
        ),
    ]
