# Generated by Django 3.0 on 2020-03-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
