# Generated by Django 3.0 on 2020-03-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_auto_20200325_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=250),
        ),
    ]
