# Generated by Django 3.0 on 2020-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_auto_20200325_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, upload_to='fashion')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('paragraph', models.TextField()),
                ('user_name', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, upload_to='food')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('paragraph', models.TextField()),
                ('user_name', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, upload_to='travel')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('paragraph', models.TextField()),
                ('user_name', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, upload_to='vlog')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('paragraph', models.TextField()),
                ('user_name', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
