# Generated by Django 3.0 on 2020-03-26 05:55

import HomePage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_auto_20200326_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_photo',
            field=models.ImageField(blank=True, help_text='The images files size must be greater than 200kb and less than 500kb. The dimensions of the photograph should be 800 (width) x 800 (height)', upload_to='events', validators=[HomePage.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250),
        ),
    ]
