# Generated by Django 3.0 on 2020-03-26 06:50

import HomePage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_auto_20200326_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(blank=True, upload_to='health', validators=[HomePage.models.validate_image])),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Diet', 'Diet'), ('Yoga', 'Yoga'), ('Health & Wellness', 'Health & Wellness'), ('Naturopathy', 'Naturopathy')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('paragraph', models.TextField()),
                ('user_name', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
