# Generated by Django 3.0.4 on 2020-03-28 06:32

import HomePage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomePage', '0011_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('user_post_image', models.ImageField(blank=True, help_text='The images files size must be greater than 200kb and less than 500kb. The dimensions of the photograph should be 800 (width) x 800 (height)', upload_to='user_posts/user_post_images', validators=[HomePage.models.validate_image])),
                ('user_post_url', models.URLField(blank=True, help_text='Note: Add https:// in the URL, Example: https://youtu.be/r2Hvxr7esNM ', unique=True)),
                ('user_post_attachment', models.FileField(upload_to='user_posts/user_post_documents')),
                ('user_post_location', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
