# Generated by Django 3.0.4 on 2020-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0013_userpostmessage_user_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmessage',
            name='user_post_attachment',
            field=models.FileField(blank=True, upload_to='user_posts/user_post_documents'),
        ),
    ]
