# Generated by Django 3.0.4 on 2020-03-28 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0014_auto_20200328_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostmessage',
            old_name='user_message',
            new_name='user_post_message',
        ),
        migrations.RemoveField(
            model_name='userpostmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='userpostmessage',
            name='user_name_post',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
