# Generated by Django 3.0.4 on 2020-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0016_auto_20200329_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_site',
            field=models.URLField(blank=True, help_text='Note: Add https:// in the URL, Example: https://youtu.be/r2Hvxr7esNM '),
        ),
    ]
