# Generated by Django 3.0.4 on 2020-03-29 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0017_auto_20200329_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_about_me',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.DateTimeField(blank=True, help_text='YYYY-MM-DD format', null=True),
        ),
    ]
