# Generated by Django 3.0.4 on 2020-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0019_auto_20200330_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100),
        ),
    ]
