# Generated by Django 3.0.4 on 2020-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0020_auto_20200330_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
