# Generated by Django 3.0.4 on 2020-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0023_auto_20200331_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Select', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_rating',
            field=models.CharField(default='Bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Select', max_length=20),
        ),
    ]
