# Generated by Django 3.0.4 on 2020-03-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0024_auto_20200331_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('News', 'News'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_rating',
            field=models.CharField(default='Bronze', max_length=100),
        ),
    ]
