# Generated by Django 3.0.4 on 2020-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0025_auto_20200331_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100),
        ),
    ]
