# Generated by Django 3.0.4 on 2020-04-03 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomePage', '0030_auto_20200402_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo_1', models.ImageField(blank=True, upload_to='User Blog')),
                ('user_photo_2', models.ImageField(blank=True, upload_to='User Blog')),
                ('user_photo_3', models.ImageField(blank=True, upload_to='User Blog')),
                ('user_photo_4', models.ImageField(blank=True, upload_to='User Blog')),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel')], max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('user_paragraph_1', models.TextField()),
                ('user_paragraph_2', models.TextField()),
                ('user_paragraph_3', models.TextField()),
                ('user_paragraph_4', models.TextField()),
                ('user_post_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Vlog',
        ),
    ]
