# Generated by Django 3.0.4 on 2020-04-03 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0031_auto_20200403_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='heading',
            new_name='blog_heading',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_paragraph_1',
            new_name='blog_paragraph_1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_paragraph_2',
            new_name='blog_paragraph_2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_photo_1',
            new_name='blog_photo_1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_photo_2',
            new_name='blog_photo_2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_photo_3',
            new_name='blog_photo_3',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_photo_4',
            new_name='blog_photo_4',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_post_date',
            new_name='blog_post_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_paragraph_3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_paragraph_4',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
