# Generated by Django 3.0.4 on 2020-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0032_auto_20200403_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_paragraph_2',
            field=models.TextField(blank=True),
        ),
    ]
