# Generated by Django 3.0.4 on 2020-04-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0036_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='user',
            new_name='post',
        ),
    ]
