# Generated by Django 3.0.4 on 2020-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0037_auto_20200409_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
