# Generated by Django 3.0.4 on 2020-04-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0038_auto_20200409_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fashion',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
