# Generated by Django 3.0.4 on 2020-04-10 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomePage', '0039_auto_20200410_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=350)),
                ('blog_heading', models.TextField()),
                ('blog_paragraph_1', models.TextField()),
                ('blog_paragraph_2', models.TextField(blank=True)),
                ('blog_photo_1', models.ImageField(blank=True, upload_to='User Blog')),
                ('blog_photo_2', models.ImageField(blank=True, upload_to='User Blog')),
                ('blog_photo_3', models.ImageField(blank=True, upload_to='User Blog')),
                ('blog_photo_4', models.ImageField(blank=True, upload_to='User Blog')),
                ('blog_post_date', models.DateField(auto_now_add=True)),
                ('super_user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=100),
        ),
    ]
