# Generated by Django 3.0.4 on 2020-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0041_auto_20200410_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='blog_category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('Lifestyle', 'Lifestyle'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=350),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('Lifestyle', 'Lifestyle'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Event & Entertainment', 'Event & Entertainment'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('Lifestyle', 'Lifestyle'), ('News', 'News'), ('Computer Programming', 'Computer Programming'), ('Politics', 'Politics'), ('Shopping', 'Shopping'), ('Social Welfare', 'Social Welfare'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=100),
        ),
    ]
