# Generated by Django 3.0.4 on 2020-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0043_auto_20200410_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_published_status',
            field=models.BooleanField(default=False),
        ),
    ]
