# Generated by Django 3.0.4 on 2020-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0044_blog_blog_published_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='blog_published_status',
            field=models.BooleanField(default=False),
        ),
    ]
