# Generated by Django 3.0.4 on 2020-04-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0046_auto_20200415_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
