# Generated by Django 3.0.4 on 2020-04-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0050_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='subscribe',
        ),
    ]
