# Generated by Django 3.0.4 on 2020-04-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0051_auto_20200422_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=500)),
                ('ad_image', models.ImageField(blank=True, upload_to='AdminPost/ads')),
            ],
        ),
    ]
