# Generated by Django 3.0.4 on 2020-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0052_dsad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsad',
            name='ad_category',
            field=models.CharField(blank=True, choices=[('Right-Side-Ad', 'Right-Side-Ad'), ('Center-Banner', 'Center-Banner')], max_length=250),
        ),
        migrations.AddField(
            model_name='dsad',
            name='ad_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsad',
            name='ad_published_status',
            field=models.BooleanField(default=False),
        ),
    ]
