# Generated by Django 3.0.4 on 2020-04-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0053_auto_20200427_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsad',
            name='ad_link',
            field=models.URLField(blank=True),
        ),
    ]
